### PR TITLE
Feature/card model and controller front end

### LINKED ISSUE #4: build client side card model and controller

### PR DESCRIPTION
**Pull request by PyNate**
closes #4

### CODE REVIEW

**Comment by kylebakerio** [comment]
I could definitely follow this rule more myself, but I think we should probably all be commenting our code more.

**Comment by PyNate** [comment]
Very true. Let me add some comments.

**Comment by kylebakerio** [comment]
It's also good practice to ensure all documents end with a newline. Probably won't cause us any problems with our particular tools, but github complains when you don't, and it is a common convention. (Was going to add this to the previous comment, but you responded so quickly!)

**Comment by PyNate** [comment]
Added comments. Ready for merge if there are no other issues.

**Pull request merged**
